hub:
  # output of second execution of 'openssl rand -hex 32'
  cookieSecret: ""
  db:
    type: sqlite-pvc
    pvc:
      accessModes:
        - ReadWriteOnce
      storage: 1Gi
      storageClassName: managed-nfs-storage
  extraConfig: |
    from kubernetes import client
    def modify_pod_hook(spawner, pod):
        pod.spec.containers[0].security_context = client.V1SecurityContext(
            privileged=True,
            capabilities=client.V1Capabilities(
                add=['SYS_ADMIN']
            )
        )
        return pod
    c.KubeSpawner.modify_pod_hook = modify_pod_hook


proxy:
  # output of second execution of 'openssl rand -hex 32'
  secretToken: ""


singleuser:
  memory:
    guarantee: 1G
    limit: 2G
  storage:
    type: none
  image:
    name: craigwillis/jupyter-singularity
    tag: latest

ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: "true"
  hosts:
    - test.ndslabs.org
  tls:
   - hosts:
      - test.ndslabs.org
     secretName: kubelego-tls-jupyterhub
